name: example
description: A simple example app for the sliding_up_panel package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../

  flutter_map: ^8.3.2
  cached_network_image: ^4.0.4
  cupertino_icons: ^2.0.0
  material_ui: ^1.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
