name: sliding_up_panel
description: A draggable Flutter widget that makes implementing a SlidingUpPanel much easier!
version: 3.0.0
homepage: https://github.com/akshathjain/sliding_up_panel

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  material_ui: 1.5.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
