name: sliding_up_panel
description: A bottom sheet that can be clicked on demand for extra content.
version: 4.0.0
homepage: https://github.com/iWisp3360/sliding_up_panel

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  material_ui: 1.5.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
